import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Game } from './game';

describe('Game component', () => {

    let numbers = ['num1', 'num2', 'num3', 'num4', 'num5', 'num6', 'num7', 'num8', 'num9', 'num10', 'num11', 'num12',
        'num13', 'num14', 'num15', 'num16', 'num17', 'num18', 'num19', 'num20', 'num21', 'num22', 'num23', 'num24'];

    test('should display game component', () => {
        render(<Game numbers={numbers}/>);
        expect(screen.getByTestId('game-component')).toBeVisible();
    });

    test('should display footer text after choosing all boxes and no-deal cases', () => {
        render(<Game numbers={numbers} />);
        const box1 = screen.getByText('1');
        const box2 = screen.getByText('2');
        const box3 = screen.getByText('3');
        const box4 = screen.getByText('4');
        const box5 = screen.getByText('5');
        const box6 = screen.getByText('6');
        const box7 = screen.getByText('7');
        const box8 = screen.getByText('8');
        const box9 = screen.getByText('9');
        const box10 = screen.getByText('10');
        const box11 = screen.getByText('11');
        const box12 = screen.getByText('12');
        const box13 = screen.getByText('13');
        const box14 = screen.getByText('14');
        const box15 = screen.getByText('15');
        const box16 = screen.getByText('16');
        const box17 = screen.getByText('17');
        const box18 = screen.getByText('18');
        const box19 = screen.getByText('19');
        const box20 = screen.getByText('20');
        const box21 = screen.getByText('21');
        const box22 = screen.getByText('22');
        const box23 = screen.getByText('23');
        userEvent.click(box1);
        expect(screen.getByText('Choose 6 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box2);
        expect(screen.getByText('Choose 5 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box3);
        expect(screen.getByText('Choose 4 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box4);
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box5);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box6);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box7);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByText('Choose 4 boxes')).toBeInTheDocument();
        userEvent.click(box8);
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        userEvent.click(box9);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        userEvent.click(box10);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        userEvent.click(box11);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        userEvent.click(box12);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        userEvent.click(box13);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        userEvent.click(box14);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        userEvent.click(box15);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        userEvent.click(box16);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        userEvent.click(box17);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        userEvent.click(box18);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        userEvent.click(box19);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        userEvent.click(box20);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        userEvent.click(box21);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        userEvent.click(box22);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        userEvent.click(box23);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-no-deal-button'));
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        expect(screen.getByText('YOU WON')).toBeInTheDocument();
    });

    test('should display footer text in deal case', () => {
        render(<Game numbers={numbers} />);
        const box1 = screen.getByText('1');
        const box2 = screen.getByText('2');
        const box3 = screen.getByText('3');
        const box4 = screen.getByText('4');
        const box5 = screen.getByText('5');
        const box6 = screen.getByText('6');
        const box7 = screen.getByText('7');
        userEvent.click(box1);
        expect(screen.getByText('Choose 6 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box2);
        expect(screen.getByText('Choose 5 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box3);
        expect(screen.getByText('Choose 4 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box4);
        expect(screen.getByText('Choose 3 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box5);
        expect(screen.getByText('Choose 2 boxes')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box6);
        expect(screen.getByText('Choose 1 box')).toBeInTheDocument();
        expect(screen.queryByTestId('modal-body')).not.toBeInTheDocument();
        userEvent.click(box7);
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        userEvent.click(screen.getByTestId('modal-deal-button'));
        expect(screen.queryByTestId('footer-counter')).not.toBeVisible();
        expect(screen.getByTestId('modal-body')).toBeInTheDocument();
        expect(screen.getByText('YOU WON')).toBeInTheDocument();
    });

});
